package com.model;

/**
 * TBaoxiu generated by MyEclipse Persistence Tools
 */

/**
 * @author Administrator
 *
 */
public class TBaoxiu implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String shijian;

	private String yuanyin;

	private Integer susheId;

	private String sushe;
	
	private int stuId;

	private String zhuangtai;

	private String del;

	// Constructors

	/** default constructor */
	public TBaoxiu()
	{
	}

	/** full constructor */
	public TBaoxiu(String shijian, String yuanyin, Integer susheId,
			String sushe, String zhuangtai, String del)
	{
		this.shijian = shijian;
		this.yuanyin = yuanyin;
		this.susheId = susheId;
		this.sushe = sushe;
		this.zhuangtai = zhuangtai;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public String getYuanyin()
	{
		return this.yuanyin;
	}

	public void setYuanyin(String yuanyin)
	{
		this.yuanyin = yuanyin;
	}

	public Integer getSusheId()
	{
		return this.susheId;
	}

	public void setSusheId(Integer susheId)
	{
		this.susheId = susheId;
	}


	public int getStuId()
	{
		return stuId;
	}

	public void setStuId(int stuId)
	{
		this.stuId = stuId;
	}

	public String getSushe()
	{
		return this.sushe;
	}

	public void setSushe(String sushe)
	{
		this.sushe = sushe;
	}

	public String getZhuangtai()
	{
		return this.zhuangtai;
	}

	public void setZhuangtai(String zhuangtai)
	{
		this.zhuangtai = zhuangtai;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}