package com.model;

/**
 * TLaifang generated by MyEclipse Persistence Tools
 */

public class TLaifang implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String laishijian;

	private String qushijian;

	private String laifangzhe;

	private Integer susheId;

	private String suoqusushe;

	private String del;

	// Constructors

	/** default constructor */
	public TLaifang()
	{
	}

	/** full constructor */
	public TLaifang(String laishijian, String qushijian, String laifangzhe,
			Integer susheId, String suoqusushe, String del)
	{
		this.laishijian = laishijian;
		this.qushijian = qushijian;
		this.laifangzhe = laifangzhe;
		this.susheId = susheId;
		this.suoqusushe = suoqusushe;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLaishijian()
	{
		return this.laishijian;
	}

	public void setLaishijian(String laishijian)
	{
		this.laishijian = laishijian;
	}

	public String getQushijian()
	{
		return this.qushijian;
	}

	public void setQushijian(String qushijian)
	{
		this.qushijian = qushijian;
	}

	public String getLaifangzhe()
	{
		return this.laifangzhe;
	}

	public void setLaifangzhe(String laifangzhe)
	{
		this.laifangzhe = laifangzhe;
	}

	public Integer getSusheId()
	{
		return this.susheId;
	}

	public void setSusheId(Integer susheId)
	{
		this.susheId = susheId;
	}

	public String getSuoqusushe()
	{
		return this.suoqusushe;
	}

	public void setSuoqusushe(String suoqusushe)
	{
		this.suoqusushe = suoqusushe;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}