package com.model;

/**
 * TShijian generated by MyEclipse Persistence Tools
 */

public class TShijian implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String shijian;

	// Constructors

	/** default constructor */
	public TShijian()
	{
	}

	/** full constructor */
	public TShijian(String shijian)
	{
		this.shijian = shijian;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

}