package com.model;

/**
 * TSuzhe generated by MyEclipse Persistence Tools
 */

public class TSushe implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String fangjianhao;

	private Integer xueshengrenshu;

	private String xueshengbanji;

	private String louhao;

	private String del;

	// Constructors

	/** default constructor */
	public TSushe()
	{
	}

	/** full constructor */
	public TSushe(String fangjianhao, Integer xueshengrenshu,
			String xueshengbanji, String louhao, String del)
	{
		this.fangjianhao = fangjianhao;
		this.xueshengrenshu = xueshengrenshu;
		this.xueshengbanji = xueshengbanji;
		this.louhao = louhao;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getFangjianhao()
	{
		return this.fangjianhao;
	}

	public void setFangjianhao(String fangjianhao)
	{
		this.fangjianhao = fangjianhao;
	}

	public Integer getXueshengrenshu()
	{
		return this.xueshengrenshu;
	}

	public void setXueshengrenshu(Integer xueshengrenshu)
	{
		this.xueshengrenshu = xueshengrenshu;
	}

	public String getXueshengbanji()
	{
		return this.xueshengbanji;
	}

	public void setXueshengbanji(String xueshengbanji)
	{
		this.xueshengbanji = xueshengbanji;
	}

	public String getLouhao()
	{
		return this.louhao;
	}

	public void setLouhao(String louhao)
	{
		this.louhao = louhao;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}