package com.model;

/**
 * TWeisheng generated by MyEclipse Persistence Tools
 */

public class TWeisheng implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String shijian;

	private Integer susheId;

	private String sushe;

	private Integer fenshu;

	private String beizhu;

	private String del;

	// Constructors

	/** default constructor */
	public TWeisheng()
	{
	}

	/** full constructor */
	public TWeisheng(String shijian, Integer susheId, String sushe,
			Integer fenshu, String beizhu, String del)
	{
		this.shijian = shijian;
		this.susheId = susheId;
		this.sushe = sushe;
		this.fenshu = fenshu;
		this.beizhu = beizhu;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public Integer getSusheId()
	{
		return this.susheId;
	}

	public void setSusheId(Integer susheId)
	{
		this.susheId = susheId;
	}

	public String getSushe()
	{
		return this.sushe;
	}

	public void setSushe(String sushe)
	{
		this.sushe = sushe;
	}

	public Integer getFenshu()
	{
		return this.fenshu;
	}

	public void setFenshu(Integer fenshu)
	{
		this.fenshu = fenshu;
	}

	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}